using System.Text;
using System.Xml.Linq;

namespace CountryGenerator
{
    public class Program
    {
        private static string _namespace = "MagmaWorks.Taxonomy.Countries";
        private static string _indt = "    ";
        public static void Main()
        {
            // Relative path to data
            string path = "../../../CountriesData.csv";
            // read data, skip header row
            List<CsvValues> values = File.ReadAllLines(path).Skip(1)
                                     .Select(v => CsvValues.FromCsv(v))
                                     .ToList();

            var directory = Directory.GetParent(path).Parent;
            path = Path.Combine(directory.FullName, "Countries", "AutoGenerated");
            Directory.CreateDirectory(path);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine($"namespace {_namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"{_indt}public enum Country");
            sb.AppendLine($"{_indt}{{");
            foreach (CsvValues v in values)
            {
                ClassWriter.WriteClass(v, path, _namespace);
                string className = ClassWriter.ToPascalCase(v.Name);
                sb.AppendLine($"{_indt}{_indt}{className},");
            }

            sb.AppendLine($"{_indt}}}");
            sb.AppendLine("}");
            var file = new StreamWriter($"{path}/Country.cs");
            file.Write(sb);
            file.Close();
        }
    }
}
