using System.Text;

namespace CatalogueProfileGenerator
{
    public class Program
    {
        private static string _namespace = "MagmaWorks.Taxonomy.Profiles";
        private static string _indt = "    ";
        public static void Main()
        {
            ConvertCsv("EN10365-2017", "European");
        }

        private static void ConvertCsv(string csvName, string catalogue)
        {
            // Relative path to data
            string path = $"../../../{csvName}.csv";
            // read data, skip header row
            List<CsvValues> values = File.ReadAllLines(path).Skip(1)
                                     .Select(v => CsvValues.FromCsv(v))
                                     .ToList();

            var directory = Directory.GetParent(path).Parent;
            path = Path.Combine(directory.FullName, "CatalogueProfiles", catalogue, "AutoGenerated");
            Directory.CreateDirectory(path);
            var enums = new StringBuilder();
            foreach (CsvValues v in values)
            {
                ClassWriter.WriteEN10365Class(v, path, _namespace);
                string className = ClassWriter.CreateClassName(v.Designation);
                enums.AppendLine($"{_indt}{_indt}{className},");
            }

            var sb = new StringBuilder();
            sb.AppendLine(
$@"namespace {_namespace}
{{
    public enum {catalogue}
    {{
{enums}
    }}
}}
");
            path = Path.Combine(directory.FullName, "CatalogueProfiles", catalogue);
            var file = new StreamWriter($"{path}/{catalogue}.cs");
            file.Write(sb);
            file.Close();
        }
    }
}
