global using System;
global using MagmaWorks.Taxonomy.Materials;
global using MagmaWorks.Taxonomy.Materials.StandardMaterials.En;
global using MagmaWorks.Taxonomy.Standards;
global using MagmaWorks.Taxonomy.Standards.Eurocode;
global using UnitsNet;
global using UnitsNet.Units;
global using Xunit;
global using Stress = UnitsNet.Pressure;
global using Strain = UnitsNet.Ratio;
global using StressUnit = UnitsNet.Units.PressureUnit;
global using StrainUnit = UnitsNet.Units.RatioUnit;
