name: CI using shared actions

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]
  release:
    types: [published]

jobs:
  ci:
    uses: MagmaWorks/Actions/.github/workflows/ci-dotnet.yml@main
    secrets: inherit
