name: Package and draft release

on:
  push:
    branches:
    - main
    
jobs:
  build_test_package:
    name: Build, test, package and upload artifact
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ""
    
    - name: Package
      run: dotnet pack -c Release --no-restore --include-symbols

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./**/*.nupkg"
        tag: ${{ steps.tag_version.outputs.new_tag }}
        draft: true
        updateOnlyUnreleased: true
