name: Package and draft release

on:
  push:
    branches:
    - main
    
jobs:
  build_test_package:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test
      run: dotnet test --configuration Release --no-build
    
    - name: Package
      run: dotnet pack
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
          name: NuGet packages
          path: ./**/*.nupkg
