name: On Merge to Main -- Package and create/update draft release

on:
  push:
    branches:
    - main
    
jobs:
  build_test_package:
    name: Build, test, package and create release
    runs-on: ubuntu-latest
    steps:
        
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test
      run: dotnet test --configuration Release --no-build
    
    - name: Package
      run: dotnet pack --configuration Release --no-restore -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg /p:DebugType=portable /property:Configuration=Debug

    - name: Get version from Package name
      id: get_version
      shell: pwsh
      run: |
        $fullVersion = [array]$($(Get-ChildItem -recurse -Filter *.nupkg | Select-Object -First 1).Name -split '(?=\d)',2)[1].replace('.nupkg','').split('.')
        $majorVersion = [string]$fullVersion[0]
        $minorVersion = [string]$fullVersion[1]
        $patchVersion = [string]$fullVersion[2]
        $dotSeparatedTag = $majorVersion + "." + $minorVersion + "." + $patchVersion
        echo version=$dotSeparatedTag >> "$GITHUB_OUTPUT"

    - name: Debug
      run: echo ${{ steps.get_version.outputs.version }}
      
    - name: Create new draft release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./**/*.*nupkg"
        tag: ${{ steps.get_version.outputs.version }}
        draft: true
        allowUpdates: true
        updateOnlyUnreleased: true
