name: On Merge to Main -- Package and create/update draft release

on:
  push:
    branches:
    - main
    
jobs:
  merge-to-main-ci:
    uses: magmaworks/actions/.github/workflows/on-merge-to-main.yml@main
