name: On Release -- Push NuGet

on:
  release:
    types: [published]

jobs:
  build_test_package:
    name: Build, test, and package
    runs-on: ubuntu-latest
    steps:

    - name: Get version from Release tag name
      id: get_version
      shell: pwsh
      run: |
        $fullVersion = [array]$(${{ github.event.release.tag_name }}).Name.split('.')
        $majorVersion = [string]$fullVersion[0]
        $minorVersion = [string]$fullVersion[1]
        $patchVersion = [string]$fullVersion[2]
        $buildVersion = [string]$fullVersion[3]
        $versionTag = $majorVersion + "." + $minorVersion + "." + $patchVersion
        echo "VERSION=$versionTag" >> $env:GITHUB_OUTPUT
        echo "Version: $versionTag"
    
    - name: Create Major.Minor.Patch tag
      run: |
        git tag ${{ steps.get_version.outputs.VERSION }}
        git push --tags
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0

    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test
      run: dotnet test --configuration Release --no-build
    
    - name: Package
      run: dotnet pack --configuration Release --no-restore -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg /p:DebugType=portable /property:Configuration=Debug

    - name: Update release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./**/*.*nupkg"
        tag: ${{ github.event.release.tag_name }}
        draft: false
        allowUpdates: true
        removeArtifacts: true
        updateOnlyUnreleased: false

#    - name: Push nupkg file to nuget.org
#      run: dotnet nuget push "*.nupkg" --api-key ${{ SECRETS.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
