name: spell-check
on:
  push:
    branches: [main, release-*]
  pull_request:
jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx cspell@v5 "**/*"
